"""empty message

Revision ID: a45f0eba24aa
Revises: 6ae9207fbfa0
Create Date: 2022-08-12 13:54:18.145314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45f0eba24aa'
down_revision = '6ae9207fbfa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_link', sa.String(length=500), nullable=True))
    op.add_column('artist', sa.Column('need_venues', sa.Boolean(), nullable=False))
    op.add_column('artist', sa.Column('venue_description', sa.String(length=600), nullable=False))
    op.add_column('venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('website_link', sa.String(length=500), nullable=True))
    op.add_column('venue', sa.Column('need_talents', sa.Boolean(), nullable=False))
    op.add_column('venue', sa.Column('talent_description', sa.String(length=600), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'talent_description')
    op.drop_column('venue', 'need_talents')
    op.drop_column('venue', 'website_link')
    op.drop_column('venue', 'genres')
    op.drop_column('artist', 'venue_description')
    op.drop_column('artist', 'need_venues')
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###
