"""empty message

Revision ID: dc60c86baafd
Revises: e6e2fba152fd
Create Date: 2022-08-12 23:01:58.406952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc60c86baafd'
down_revision = 'e6e2fba152fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'need_venues',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('artist', 'venue_description',
               existing_type=sa.VARCHAR(length=600),
               nullable=True)
    op.alter_column('venue', 'need_talents',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('venue', 'talent_description',
               existing_type=sa.VARCHAR(length=600),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'talent_description',
               existing_type=sa.VARCHAR(length=600),
               nullable=False)
    op.alter_column('venue', 'need_talents',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('artist', 'venue_description',
               existing_type=sa.VARCHAR(length=600),
               nullable=False)
    op.alter_column('artist', 'need_venues',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
